# -*- coding: utf-8 -*-
"""ejemplost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewazOlcdpJ0Rrhff-FBorSMKwHwrDgiv
"""

import streamlit as st

st.write('Hello,*World!* :sunglasses:')